### PR TITLE
Fix build setup when MEEP is not available

### PR DESCRIPTION
**Pull request by philippwindischhofer**
See https://github.com/eisvogel-project/Eisvogel/issues/50, thanks @tamasgal for reporting!

### CODE REVIEW

**Comment by tamasgal** [comment]
Perfect, thanks for the quick fix :)

**Comment by philippwindischhofer** [comment]
No problem! I never ran into this since I always compiled locally with MEEP. Added to the CI now, should catch this (and similar problems) in the future.

**Comment by tamasgal** [comment]
I see. Currently I am trying to use the Conda distribution of MEEP on our cluster because building MEEP locally is a major effort (and they recommend the Conda-way). Maybe that's the wrong way to use Eisvogel though?

**Comment by tamasgal** [comment]
Btw. with this branch I am now at:

```shell
(meeptest) ✔ ~/dev/Eisvogel/build [phwindis_fix_nomeep_build|✔]
16:28 $ make
[  3%] Building CXX object examples/dipole_free_space/CMakeFiles/dipole_free_space.dir/dipole_free_space.cxx.o
In file included from /home/hpc/capn/mpo1217/dev/Eisvogel/eisvogel/core/AnalyticGreensFunctionCalculator.hh:4,
                 from /home/hpc/capn/mpo1217/dev/Eisvogel/examples/dipole_free_space/dipole_free_space.cxx:2:
/home/hpc/capn/mpo1217/dev/Eisvogel/eisvogel/core/impl/Vector.hh:6:10: fatal error: execution: No such file or directory
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by philippwindischhofer** [comment]
Are you using a compiler with full C++20 support?

https://en.cppreference.com/w/cpp/compiler_support

**Comment by tamasgal** [comment]
Apparently format is in GCC 13 (experimental) and I assume GCC 14 is what you use and there it's fully supported?

**Comment by philippwindischhofer** [comment]
We've been using gcc 13 so far (both for development and in the CI).

**Comment by tamasgal** [comment]
Oh OK I see. So I need to compile a new compiler first on our HPC.

**Comment by philippwindischhofer** [comment]
Maybe it's worth checking if your administrators are keen on providing a systemwide gcc-13 module?

**Comment by philippwindischhofer** [comment]
In the meantime, let me merge this PR (which was clearly an issue that needed fixing).

**Comment by tamasgal** [comment]
Yes, already in contact with them. Thanks again!

**Comment by philippwindischhofer** [comment]
Sure! Let me know how you get on, and don't hesitate to write again (here or elsewhere) if there are any other things that are unclear or need fixing :-)

**Comment by tamasgal** [comment]
Yes, I will 🙂

**Comment by tamasgal** [comment]
Successfully built with GCC 13.3.0 :)

**Pull request merged**
